### ISSUE TITLE
Classifai screen stuck when import empty folder

### ISSUE THREAD

**Issue by codenamewei** [CertifaiAI/classifai#223]
**To Reproduce**
Import an empty folder

**Expected behavior**
Back to labelling tool without error

**Screenshots**
![Capture](https://user-images.githubusercontent.com/33477318/99144986-cd414c00-26a5-11eb-9b37-19e668d7fb06.JPG)

**Desktop (please complete the following information):**
 - Windows
- v1.0.0

**Comment by codenamewei** [comment]
Not particularly urgent, doesnt need to complete in this week. will include in v1.1.0 as fix 

Work on this when docs for open sources are almost done or pending my feedback 

Please base the fix from this branch https://github.com/CertifaiAI/classifai/tree/v1.1.0

Thanks @toh-sie-hung

**Comment by toh-sie-hung** [comment]
okay, sure

**Comment by codenamewei** [comment]
Resolved with #226
