### ISSUE TITLE
Certain jpg file not readable

### ISSUE THREAD

**Issue by YCCertifai** [CertifaiAI/classifai#280]
**Describe the bug**
https://drive.google.com/drive/folders/1yn_4Abu-5xTr8vdzFPUVJOApt3gjCWw5?usp=sharing
This particular folder of image is an example of not readable jpg image.
Will cause server down.

**To Reproduce**
1. Download this image.
2. Upload it to classifai

**Expected behavior**
Able to read the image.
Or
Do not cause server down.

**Screenshots**
![Screenshot from 2021-01-22 08-22-04](https://user-images.githubusercontent.com/76682536/105429712-eb6e8e00-5c8c-11eb-89b2-b54702c7fb0d.png)

**Desktop (please complete the following information):**
 - OS: Windows, Ubuntu
 - Browser chromium
 - Version 1.1.0

**Additional context**

**Comment by BobbyLCW** [comment]
![image](https://user-images.githubusercontent.com/43332142/105430319-3046f480-5c8e-11eb-9021-b52d27a4b789.png)
Don't get your issue. My classifai is able to read it.

**Comment by BobbyLCW** [comment]
![image](https://user-images.githubusercontent.com/43332142/105430544-b105f080-5c8e-11eb-92f8-5902df675674.png)

Even try with upload whole folder.

**Comment by YCCertifai** [comment]
It does not work in my pc and another person pc thou..
Will make further invetigation..
Thanks for the info.

**Comment by BobbyLCW** [comment]
@kengeSkyMind can u lent a hand to YC regarding this issue? thanks.

**Comment by kengeSkyMind** [comment]
tried it on both Windows and Ubuntu20 VM, cannot recreate the bug

**Comment by YCCertifai** [comment]
https://drive.google.com/drive/folders/1yn_4Abu-5xTr8vdzFPUVJOApt3gjCWw5?usp=sharing
@BobbyLCW This is the original folder that failed to import... 
FYI, it fails to import on kenge pc as well...
