### ISSUE TITLE
All images data are stored in segmentation database

### ISSUE THREAD

**Issue by YCCertifai** [CertifaiAI/classifai#332]
bounding box projects' images data are stored in segmentation database.
![classifaiPortfolioDb](https://user-images.githubusercontent.com/76682536/112406129-8b5c9c80-8d4e-11eb-9933-c15697c04dbd.png)
![classifaiAnnotationDb](https://user-images.githubusercontent.com/76682536/112406140-8ef02380-8d4e-11eb-8a18-0365e038a771.png)

From what I investigated, this could be the reason:
jdbcPool written is a static field, and it "lives" with the class not the object. 
https://github.com/CertifaiAI/classifai/blob/cw_importexport/classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java#L62

During deployment of verticles, segmentation is deployed after bounding box, therefore all sub classes of annotation verticle are connected to segmentation database.
https://github.com/CertifaiAI/classifai/blob/cw_importexport/classifai-core/src/main/java/ai/classifai/MainVerticle.java#L69-L79

Solution:
change jdbcPool to a non-static field will fix the problem.

**Comment by codenamewei** [comment]
good catch, will wait for the fix.

**Comment by codenamewei** [comment]
workaround implemented
