### ISSUE TITLE
Deleting of images cause the losses of annotations

### ISSUE THREAD

**Issue by codenamewei** [CertifaiAI/classifai#380]
Classifai Distribution https://drive.google.com/file/d/1DM2xT1Si3Op27JIHI5vH-tPsGVQ4fbO6/view?usp=sharing

1. Import project of n images
2. Start annotations on a few images (more than 10)
3. Close classifai
4. Remove an image (that is not labelled) from the OS default item selector
5. Restart classifai and open back the project 
6. All traces of annotation on other previously labelled images gone.

Happens on system of
core: intel i5
ram: 4
storage: 111GB
os: windows 10 home

**Comment by AdrySky** [comment]
@codenamewei I did the debugging and found **no issue** with the losses of annotations when removing an image that is not labelled from the OS default item selector, as my other labelled images are still there with their annotations.

**Comment by devenyantis** [comment]
You can download the dataset used by [her](https://drive.google.com/file/d/1OKQ30hgjnBbA3TNZLGB_yfI12CQmF9W2/view?usp=sharing)

**Comment by codenamewei** [comment]
> @codenamewei I did the debugging and found **no issue** with the losses of annotations when removing an image that is not labelled from the OS default item selector, as my other labelled images are still there with their annotations.

@AdrySky thanks for update.. let us know after testing with her dataset. 

if still not seeing the problem, ill unassign you from the task.

**Comment by ken479** [comment]
@codenamewei I have tried out self-made dataset of 30 images and also client's large car dataset. After I did annotations on images, close classifai and repeated multiple times delete the not labelled images from OS default item selector. The labels in labelled images are remained intact.

**Comment by devenyantis** [comment]
The reload functionality (Add/Remove images) is working fine. 

The problem is when performing annotation, `update api /:annotation_type/projects/:project_name/uuid/:uuid/update` is not called. In normal use, this should update the database.
So, we try opening `localhost:9999` using google chrome, and it works.
