### ISSUE TITLE
Cannot access newly added images  

### ISSUE THREAD

**Issue by ken479** [CertifaiAI/classifai#388]
**Description on bug:**
After adding in some new images into the original folder. The project column showed there are increased in number of images, however, cannot click on the new images to access it. 

**To Reproduce**
1. Download and add a few new images into the original folder that use to do image annotation.
2. Open Classifai, check if there is increased in number of images in the project
3. Try to access the newly added images in the project column

**Expected Behavior**
Should be able to access newly add images 

**Screenshots**
**Original folder:**

![Screenshot (47)](https://user-images.githubusercontent.com/84906841/119937218-fd569980-bfbc-11eb-8e20-fa218d55c67e.png)

**Add in new images:**

![Screenshot (48)](https://user-images.githubusercontent.com/84906841/119937252-0f383c80-bfbd-11eb-9640-27c1e7080dc0.png)

**Try to access new images in project column:**

![Screenshot (52)](https://user-images.githubusercontent.com/84906841/119937875-16137f00-bfbe-11eb-87d2-d2cca45297b6.png)

**Desktop**
- OS: Window 10
- Browser: Chromium
- Version: 2.0.0 alpha

**Comment by ken479** [comment]
@AdrySky I have tried a few times and found same issue happened.

**Comment by codenamewei** [comment]
@AdrySky can you confirm you are seeing it too? thank you

**Comment by YCCertifai** [comment]
@ken479  did you try the reload button?

![image](https://user-images.githubusercontent.com/76682536/119939534-9aff9800-bfc0-11eb-8f61-6dafba25ce00.png)

**Comment by ken479** [comment]
@codenamewei @YCCertifai @AdrySky Hi, Issue solved. Have to click reload button every time added new images.

**Comment by ken479** [comment]
**Documentation:**
**Image annotation** have made performed effectively and time saving with **Classifai** 

**Classifai features:**
**1) Project export and import**
Project are export and import in **json format**. When user finish image labelling, project can be exported as config file (json) or zip file (json and data). The exported file will contained all the information of the images such as annotation, date, type and image path. Similarly, when user import project in json format, all the labelled images will be showing in Classifai. 

**2) Label export and import**
All the labels will be imported when user import the project. Label of images could be exported (save as) format such as **Pascal VOC, YOLO, Text OCR and text label.**

**Attention:**
Whenever user have made **documents change or added new images** to user's project folder, it is very important that the "**reload button**" should be clicked for project refresh to avoid unable to access the updated files.

![Doc2](https://user-images.githubusercontent.com/84906841/119956153-5f21fe00-bfd3-11eb-9a95-9a70ee8a5f8e.jpg)
