### ISSUE TITLE
Some jpg file fail to load

### ISSUE THREAD

**Issue by devenyantis** [CertifaiAI/classifai#394]
**Describe the bug**
Some jpg images are skipped due to detected as different type. Skipped images are jpg image according to name. All images can be opened and viewed on Windows.

**To Reproduce**
1. Create new project
2. Use the dataset given. [Download here.](https://drive.google.com/drive/folders/1dTvbIz7NqI-b6R2em3AjPa_xnUYt3HaL?usp=sharing) I included one valid jpg image. Others are invalid.

**Expected behavior**
All image successfully loaded

**Screenshots**
Valid image type - Detected as jpg
![Capture2](https://user-images.githubusercontent.com/69179469/120453611-c7068900-c3c5-11eb-9561-1cca9edfbb74.PNG)

Invalid image type - Detected as WebP
![Capture](https://user-images.githubusercontent.com/69179469/120453649-cf5ec400-c3c5-11eb-8f85-6f1712ed950e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium

**Additional context**
These images are from vehicleplate labellers.

**Comment by YCCertifai** [comment]
After discussion with the team, will allow webp image format in future.
