### ISSUE TITLE
Number of image displayed is wrong in project if invalid files are present 

### ISSUE THREAD

**Issue by YCCertifai** [CertifaiAI/classifai#395]
**Describe the bug**
Extending from #394, in the project interface of the project we can see that the total number of images in the project is 5 instead of 1. 

If the invalid images are deleted from the file system, the total number of images become 1.

**To Reproduce**
1. Download the [dataset](https://drive.google.com/drive/folders/1dTvbIz7NqI-b6R2em3AjPa_xnUYt3HaL?usp=sharing).
2. Create a new project using the dataset.
3. Open the project created and you will see the total number of images is 5
4. Delete all images except `valid.jpg`
5. Refresh the browser and open the project again. You will see the total number of images is correct now

**Expected behavior**
Only display the number of valid images, in this case, it must always be 1.

**Screenshots**
When invalid images are present.
![image](https://user-images.githubusercontent.com/76682536/120608947-4fe3fa00-c484-11eb-81db-10d9b7c69872.png)
When invalid images are absent.
![image](https://user-images.githubusercontent.com/76682536/120609256-98031c80-c484-11eb-826b-f3a857d27a7c.png)

**Comment by devenyantis** [comment]
For this problem, you can explore this part
https://github.com/CertifaiAI/classifai/blob/7e92193bd06c9f36ede221212fde9416d550992e/classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java#L390-L430

In particular, the checker decides if it is a valid image based on file extension.
