### ISSUE TITLE
Include project name in workspace page

### ISSUE THREAD

**Issue by devenyantis** [CertifaiAI/classifai#402]
**Is your feature request related to a problem? Please describe.**
No. The feature is good to have for better navigation.

**Describe the solution you'd like**
Add the project name somewhere in the workspace page. Probably on the top left besides image name, or top right replacing "Project". Refer picture below.

**Describe alternatives you've considered**
There is no way to know the project name from the workspace page.

**Additional context**
![Capture](https://user-images.githubusercontent.com/69179469/121319692-09d4dd80-c93f-11eb-9901-1f5a7e3d8350.PNG)
![Capture2](https://user-images.githubusercontent.com/69179469/121319699-0b9ea100-c93f-11eb-961d-a57b05bc82ec.PNG)

**Comment by amalsyahmi-certifai** [comment]
Suggest to put the project name at image labelling footer, as shown in the image below.

![image](https://user-images.githubusercontent.com/76939137/121330403-8fa95680-c948-11eb-9990-ebb4e2a514bd.png)

**Comment by devenyantis** [comment]
> Suggest to put the project name at image labelling footer, as shown in the image below.
> 
> ![image](https://user-images.githubusercontent.com/76939137/121330403-8fa95680-c948-11eb-9990-ebb4e2a514bd.png)

Great. I'm okay with that.
