### ISSUE TITLE
Conversion of pdf -> jpg/png did not run with 0% progress 

### ISSUE THREAD

**Issue by codenamewei** [CertifaiAI/classifai#418]
**Describe the bug**
Conversion holds at 0% and no files been converted.

pdf - > png

the behaviour is intermittent

branch: v2_alpha

**Comment by codenamewei** [comment]
@devenyantis can you check if you are seeing the same issue? 

if you need the same amount of dataset (pdf) to test it out let me know

**Comment by devenyantis** [comment]
Stick to 2.0.22. Closing this PR
