### ISSUE TITLE
Label Name Ending with Unrelated Character \r

### ISSUE THREAD

**Issue by hansheng0512** [CertifaiAI/classifai#437]
**Describe the bug**
Label name will include `\r` at the end,

**To Reproduce**
1. Create a label.txt,
2. Create new project named as `test1`.
2. Perform labelling.
3. Export config file.
4. Delete `test1` project.
5. Import project from json.

**Expected behavior**
Label name and config file with no `\r`

**Screenshots**

https://user-images.githubusercontent.com/81958029/123201074-92797f00-d4e4-11eb-9cee-9ab77fc4e74f.mp4

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome
 - Version: 91.0

**Additional context**
Maybe something related to CRLF/CF

**Comment by codenamewei** [comment]
hi @hansheng0512 

do you still have the label.txt with you? if yes can you attach it in here for

also do you recall that is the label.txt file created from classifai? or generated from own means?

**Comment by hansheng0512** [comment]
@codenamewei 

The label.txt is created myself like a shown in the beginning of the video.  

Here's the label file
[lbl.txt](https://github.com/CertifaiAI/classifai/files/6761259/lbl.txt)

**Comment by codenamewei** [comment]
> @codenamewei
> 
> The label.txt is created myself like I shown in the beginning of the video.
> 
> Here's the label file
> [lbl.txt](https://github.com/CertifaiAI/classifai/files/6761259/lbl.txt)

thanks will check it out
