### ISSUE TITLE
Full image path shown for Ubuntu 20.04

### ISSUE THREAD

**Issue by fariskamaludin-skymind** [CertifaiAI/classifai#446]
**Describe the bug**
![image](https://user-images.githubusercontent.com/83570177/123903760-e6330f00-d9a1-11eb-8b11-c89043c4f5f4.png)

- Image shown in full path instead of just the image name.
- Error found & tested in Ubuntu 20.04.2.0 OS, run in VirtualBox hosted by macOS 10.15.7 machine

**To Reproduce**
1. Create new project
2. See the error at the file name location

**Expected behavior**
![image](https://user-images.githubusercontent.com/83570177/123904900-dcaaa680-d9a3-11eb-9329-24aea30f963d.png)

- Can just only see the file name but not the full path of the image.
- Tested it with macOS 10.15.7 machine & it perform as expected

**Desktop (please complete the following information):**

Host Machine
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Version: Version 91

VM
- OS: Ubuntu 20.04.2.0
- Browser: Firefox Browser
- Version: 85.0.1

**Comment by hansheng000512** [comment]
This bug is solved in [this pr](https://github.com/CertifaiAI/Classifai_FrontEnd/pull/190). This update hvnt reflect in the latest distribution release.

@YCCertifai 
The latest distribution released is the TM release rite?

**Comment by YCCertifai** [comment]
@fariskamaludin-skymind is this the latest built version?

**Comment by fariskamaludin-skymind** [comment]
@YCCertifai I installed from the classifai website, https://bit.ly/3gSgd7Y, this one for the Ubuntu distribution

**Comment by YCCertifai** [comment]
I see..
as described by @hansheng000512, this bug is fixed after the distribution release.
@fariskamaludin-skymind would you like to try to build ClassifAI from the repo and see if the problem exists?
thanks

**Comment by fariskamaludin-skymind** [comment]
@YCCertifai sure, i will try the latest build from the repo and let you know if i encounter the same bug

**Comment by fariskamaludin-skymind** [comment]
latest build from the repo work as expected, will close the issue for now. Tested on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/83570177/123938694-e941f580-d9c9-11eb-8f34-874f2b09b82d.png)
