### ISSUE TITLE
Documentation update for shortcut key in different OSes

### ISSUE THREAD

**Issue by codenamewei** [CertifaiAI/classifai#454]
In regard of recent enhancement on [frontend](https://github.com/CertifaiAI/Classifai_FrontEnd/pull/194)

do work on documentation in 
- [shortcut.md](https://github.com/CertifaiAI/Classifai_FrontEnd/pull/194)
- [docs gitbook with dev branch](https://docs.classifai.ai/v/dev/product/feature-breakdown/keyboard-shortcut)

to reflect the changes

also update the [changelog](https://github.com/CertifaiAI/classifai/blob/v2_alpha/CHANGELOG.md) to track this new enhancement thanks.

**Comment by ken479** [comment]
Dear Chia Wei

Good Morning. Thank you for your email. I will proceed with the related
task.

Regards,
*Lai Yip Khen*
Junior AI Engineer
***@***.***

*Skymind Holdings Berhad*
www.skymind.global
