### ISSUE TITLE
Bounding box in v2alpha1 does not support different color for different labels.

### ISSUE THREAD

**Issue by codenamewei** [CertifaiAI/classifai#458]
**Describe the bug**
different color bbox allocated to different labels helps to identify the labels better in one glance. 

in v2alpha1, seems like everything is of color yellow.

green for current selected bounding box

v2alpha1 (v2_alphabranch)
<img width="1343" alt="Screenshot 2021-07-03 at 5 53 27 PM" src="https://user-images.githubusercontent.com/33477318/124350553-e2182300-dc27-11eb-9e46-0a109fcba37b.png">

https://classifai.vercel.app/#/

<img width="1251" alt="Screenshot 2021-07-03 at 5 54 22 PM" src="https://user-images.githubusercontent.com/33477318/124350552-dfb5c900-dc27-11eb-880e-9b5afbf4fac2.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by codenamewei** [comment]
Change to backend after db code refactoring

**Comment by yipkhenlai** [comment]
Introduce different colors for different labels #[129](https://github.com/CertifaiAI/Classifai_FrontEnd/pull/219)
