### ISSUE TITLE
Bad format for labels when importing project from config file

### ISSUE THREAD

**Issue by scotgopal** [CertifaiAI/classifai#472]
**Describe the bug**
Importing a project from a config.json modifies the labels with a suffix "\\r"

![reimport labels issue](https://user-images.githubusercontent.com/76937732/126908547-188c60dd-5d8c-49dc-a02a-a9de65a97857.png)

**To Reproduce**
1. Create new project and import a label.txt file that contents a list of labels such as "labelA", "labelB", "labelC"
2. Export project via config file (.json)
3. Delete project
4. Import the recently exported project.
5. The labels of the project will have a suffix "\\r"

**Expected behavior**
Labels without additional suffixes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: v2.0.0 alpha 1

**Additional context**

**Comment by devenyantis** [comment]
@scotgopal 
Is it possible to provide the json file?

**Comment by codenamewei** [comment]
Its solved in the v2_alpha branch [#437](https://github.com/CertifaiAI/classifai/issues/437)

To build the latest from dev branch, 
check [this](https://docs.classifai.ai/development/build-and-run-from-github-repository) out

Scot, without deleting the existing project, the new imported project will rename to an unique name,

@scotgopal @devenyantis, suggest you two  to discuss a workaround / release potentially to support your side of work
